name: Upload Website to S3

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Navigate to repo
        run: cd $GITHUB_WORKSPACE
      - name: Install Chromium Library Dependencies
        run: |
         sh ./.github/workflows/chromium-lib-install.sh
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install deps
        run: npm install
      - name: Build docs
        run: npm run build
      - name: Publish to AWS S3
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2"
          FROM_PATH: "./public"
          DEST_PATH: "s3://adh-greenwood-demo"
          OPTIONS: "--acl public-read"
