name: Firebase Deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Chromium Library Dependencies
      run: |
       sh ./.github/workflows/chromium-lib-install.sh
    - name: Build
      run: |
        npm install
        npm run build
    - name: Firebase Deploy
      run: |
        npm install -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} -P greenwood-demo
